### ISSUE TITLE
Meshrabiya security and defense against bad nodes

### ISSUE THREAD

**Issue by Darin755** [UstadMobile/Meshrabiya#9]
Does Meshrabiya have any defenses against bad nodes? Tamper protection could be achieved with encryption but routing and ddos attacks could be a serious problem. A bad actor could change the mac addresses to point to the wrong location to cause disruption or they could spoof the originating address.

**Comment by mikedawson** [comment]
No - just like TCP/IP and UDP don't have such defenses. You can have bad nodes on any normal WiFi / Ethernet network. I think this is out of scope at this layer of the network stack.
